// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package servergated

import (
	"bytes"
	"fmt"
	"github.com/fate2013/go-rtm/fp1225"
	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/fate2013/go-rtm/rtmcommon"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = fp1225.GoUnusedProtection__
var _ = rtmcommon.GoUnusedProtection__

func init() {
}
